name: Deploy Application

on:
  push:
    branches: [ master ]  # Cambiar según la rama deseada

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: "us-east-1"
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        run: |
          mkdir -p $HOME/.aws
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials

      - name: Set AWS credentials file location
        run: echo "export AWS_SHARED_CREDENTIALS_FILE=$HOME/.aws/credentials" >> $GITHUB_ENV

      - name: Verificar credenciales de AWS
        run: cat $HOME/.aws/credentials

      - name: Install dependencies
        run: cd $GITHUB_WORKSPACE/semana-3-api-cdk && npm install

      - name: Synthesize AWS CDK stack
        run: cd $GITHUB_WORKSPACE/semana-3-api-cdk && npx cdk synth

      - name: Deploy AWS CDK stack
        run: cd $GITHUB_WORKSPACE/semana-3-api-cdk && npx cdk deploy --all
